# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Xcode test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift 5.9
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.9'

      - name: Show code coverage summary
        run: |
          export SWIFT_SYNTAX_PARSER_USE_NEW_PARSER=0
          swift test --parallel
